# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'agent name')),
                ('team', models.CharField(choices=[(b'ENLIGHTENED', '\u542f\u840c\u83cc'), (b'RESISTANCE', '\u61d2\u83cc')], max_length=11, verbose_name=b'agent team')),
                ('level', models.SmallIntegerField(verbose_name=b'agent level')),
                ('sent_welcome_message', models.BooleanField(default=False, verbose_name=b'sent welcome message')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=35, verbose_name=b'message guid')),
                ('time_stamp', models.CharField(max_length=16, verbose_name=b'message time stamp')),
                ('message_type', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'message type')),
                ('agent', models.CharField(max_length=50, verbose_name=b'agent name')),
                ('team', models.CharField(blank=True, choices=[(b'ENLIGHTENED', '\u542f\u840c\u83cc'), (b'RESISTANCE', '\u61d2\u83cc')], max_length=11, null=True, verbose_name=b'agent team')),
                ('plext', models.TextField(verbose_name=b'message content')),
                ('portal_name', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'portal name')),
                ('portal_guid', models.CharField(blank=True, max_length=35, null=True, verbose_name=b'portal guid')),
                ('portal_lat', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'portal lat')),
                ('portal_lng', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'portal lng')),
                ('portal_address', models.TextField(blank=True, null=True, verbose_name=b'portal lng')),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=35, null=True, verbose_name=b'portal guid')),
                ('name', models.TextField(verbose_name=b'portal name')),
                ('latE6', models.CharField(choices=[(b'ENLIGHTENED', '\u542f\u840c\u83cc'), (b'RESISTANCE', '\u61d2\u83cc')], max_length=11, verbose_name=b'portal latitude, without decimal point')),
                ('lngE6', models.CharField(choices=[(b'ENLIGHTENED', '\u542f\u840c\u83cc'), (b'RESISTANCE', '\u61d2\u83cc')], max_length=11, verbose_name=b'portal longitude, without decimal point')),
                ('owner', models.TextField(blank=True, max_length=50, null=True, verbose_name=b'sender name')),
                ('team', models.CharField(blank=True, choices=[(b'ENLIGHTENED', '\u542f\u840c\u83cc'), (b'RESISTANCE', '\u61d2\u83cc')], max_length=11, null=True, verbose_name=b'sender team')),
                ('update_time_stamp', models.CharField(max_length=16, verbose_name=b'portal info update time stamp')),
                ('last_captured_time_stamp', models.CharField(max_length=16, verbose_name=b'portal last captured time stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6d88\u606f\u53d1\u9001\u8d26\u53f7\u540d\u5b57')),
                ('cookies', models.TextField(verbose_name='cookies')),
                ('maxLatE6', models.IntegerField(verbose_name='maxLatE6')),
                ('minLatE6', models.IntegerField(verbose_name='minLatE6')),
                ('maxLngE6', models.IntegerField(verbose_name='maxLngE6')),
                ('minLngE6', models.IntegerField(verbose_name='minLngE6')),
                ('team', models.CharField(choices=[(b'ENLIGHTENED', '\u542f\u840c\u83cc'), (b'RESISTANCE', '\u61d2\u83cc')], max_length=11, verbose_name='\u9635\u8425')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5907\u6ce8')),
                ('disable', models.BooleanField(default=False, verbose_name='\u7981\u7528')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message_send_condition', models.CharField(blank=True, choices=[(None, '\u4e0d\u53d1\u9001'), (b'freshman', '\u53ea\u53d1\u9001\u7ed9\u65b0\u6ce8\u518c\u8005'), (b'new_come', '\u53d1\u9001\u7ed9\u6240\u6709\u65b0\u5230\u6765\u8005')], default=None, max_length=10, null=True, verbose_name=b'welcome message send condition, default not send')),
                ('welcome_message', models.TextField(verbose_name=b'welcome message')),
                ('fetch_message_tab', models.CharField(choices=[(b'all', '\u6240\u6709\u6d88\u606f'), (b'faction', '\u9635\u8425\u6d88\u606f'), (b'alerts', '\u8b66\u544a\u6d88\u606f')], default=b'faction', max_length=7, verbose_name=b'fetch message tab, default faction')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IngressWatcher.Sender')),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u89c2\u5bdf\u8d26\u53f7\u540d')),
                ('cookies', models.TextField(verbose_name='cookies')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5907\u6ce8')),
                ('disable', models.BooleanField(default=False, verbose_name='\u7981\u7528')),
            ],
        ),
        migrations.CreateModel(
            name='WatchPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'watcher point name')),
                ('maxLatE6', models.IntegerField(verbose_name='maxLatE6')),
                ('minLatE6', models.IntegerField(verbose_name='minLatE6')),
                ('maxLngE6', models.IntegerField(verbose_name='maxLngE6')),
                ('minLngE6', models.IntegerField(verbose_name='minLngE6')),
                ('disable', models.BooleanField(default=False, verbose_name='\u7981\u7528')),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='watch_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IngressWatcher.WatchPoint'),
        ),
        migrations.AddField(
            model_name='setting',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IngressWatcher.Watcher'),
        ),
    ]
